services:
  server1:
    image: ubuntu:24.04
    container_name: server1
    command: sleep infinity

  server2:
    image: ubuntu:24.04
    container_name: server2
    command: sleep infinity